---
frontend_version: "{{ lookup('env','FE_VERSION') }}"
frontend_container_name: "frontend"
frontend_image_version: "{{ frontend_version }}"
frontend_container_build_path: "{{workspace}}/{{project_name}}-frontend"
frontend_dockerfile_path: "{{workspace}}/icdc-devops/docker/dockerfiles/nginx-frontend-dockerfile"
frontend_container_image: "{{ecr_repo}}/{{project_name}}-{{container_name}}:{{frontend_version}}-{{build_number}}"
frontend_container_port: 80
frontend_container_memory: 512
frontend_container_cpu: 256
frontend_container_image_url: "{{ecr_repo}}/{{project_name}}-{{container_name}}"
frontend_ecs_cluster_name: "{{ project_name }}-{{tier}}"

# logging
sumo_collector_endpoint: "{{ lookup('amazon.aws.aws_secret', 'bento/{{stack_name}}/{{tier}}.sumo_collector_endpoint', nested=true, region='us-east-1' ) }}"
sumo_collector_token: "{{ lookup('amazon.aws.aws_secret', 'bento/{{stack_name}}/{{tier}}.sumo_collector_token_fe', nested=true, region='us-east-1' ) }}"