Notes: Jenkins pipeline
project: cds
services:
  backend:
    version: 24.6.1.77
    image: 24.6.1.77
    buildNumber: '77'
  frontend:
    version: 3.0.0.91
    image: 3.0.0.91
    buildNumber: '91'
  files:
    version: 2.3.0.23
    image: 2.3.0.23
    buildNumber: '23'
