Notes: Jenkins pipeline
project: cds
services:
  backend:
    version: 24.6.1.97
    image: 24.6.1.97
    buildNumber: '97'
  frontend:
    version: 3.0.2.141
    image: 3.0.2.141
    buildNumber: '141'
  files:
    version: 2.3.1.25
    image: 2.3.1.25
    buildNumber: '25'
