Notes: Jenkins pipeline
project: cds
services:
  backend:
    version: 24.6.0.48
    image: 24.6.0.48
    buildNumber: '48'
  frontend:
    version: 2.0.0.65
    image: 2.0.0.65
    buildNumber: '65'
