Notes: Jenkins pipeline
project: cds
services:
  backend:
    version: 24.6.1.68
    image: 24.6.1.68
    buildNumber: '68'
  frontend:
    version: 3.0.0.81
    image: 3.0.0.81
    buildNumber: '81'
  files:
    version: 2.3.0-develop.20
    image: 2.3.0-develop.20
    buildNumber: '20'
