---
# defaults file for redis
redis_host: 
  dev: "bento-dev-redis-cluster.l5vrvc.clustercfg.use1.cache.amazonaws.com"
  qa: "bento-qa-redis-cluster.l5vrvc.clustercfg.use1.cache.amazonaws.com"
  perf: "bento-perf-redis-cluster.l5vrvc.clustercfg.use1.cache.amazonaws.com"
  icdc: "bento-icdc-redis-cluster.l5vrvc.clustercfg.use1.cache.amazonaws.com"
  prod: "bento-prod-redis-cluster.l5vrvc.clustercfg.use1.cache.amazonaws.com"
redis_host_icdc: 
  dev: "10.208.2.75"
  qa: "10.208.10.169"
  stage: "10.208.18.154"
  prod: "10.208.26.177"
  demo: "localhost "
redis_password: ""
redis_port: 6379
