- name: Get the current caller identity information
  aws_caller_info:
  register: caller_info

- name: set ECR registry name
  set_fact:
    ecr_repo: "{{ caller_info.account }}.dkr.ecr.{{ region }}.amazonaws.com"
    account: "{{ caller_info.account }}"

- name: login into ecr
  shell: "docker login -u AWS -p $(aws ecr get-login-password --region {{ region }}) {{ecr_repo}}"
  ignore_errors: True
  register: ecr_login