---
# vars file for cicd
env_file_home: /local/content/docker
# redis config
enable_redis: 'true'
use_cluster: 'false'
redis_host: 
  dev: "10.208.2.75"
  qa: "10.208.10.169"
  stage: "10.208.18.154"
  prod: "10.208.26.177"
redis_password: ""
redis_port: 6379
home: /local/content/docker
tier: "{{ lookup('env','TIER') }}"
platform: "cloudone"
backend_git_tag: "{{ lookup('env','BACKEND_GIT_TAG') }}"
frontend_git_tag: "{{ lookup('env','FRONTEND_GIT_TAG') }}"
frontend_version: "{{ lookup('env','FE_VERSION') }}"
docker_host: "{{ lookup('env','DOCKER_HOST') }}"
tls_hostname: "{{ lookup('env','TLS_HOSTNAME') }}"
fence_id: "{{ lookup('env','FENCE_ID') }}"
backend_version: "{{ lookup('env','BE_VERSION') }}"
workspace: "{{ lookup('env','WORKSPACE') }}"
docker_user: "{{ lookup('env','DOCKER_USER') }}"
docker_password: "{{ lookup('env','DOCKER_PASSWORD') }}"
build_number: "{{ lookup('env','BUILD_NUMBER')}}"
neo4j_ip: "{{ lookup('env','NEO4J_IP') }}"
neo4j_bearer: "{{ lookup('env','BEARER') }}"
region: us-east-1
newrelic_license_key: "{{ lookup('env','NEWRELIC_LIC_KEY')}}"
sumo_access_id: "{{ lookup('env','SUMO_ACCESS_ID')}}"
sumo_access_key: "{{ lookup('env','SUMO_ACCESS_KEY')}}"
# syslog_host: "{{ lookup('env','SYSLOG_HOST')}}"
syslog_host: "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}"
app_name: icdc-{{ platform }}-{{ tier }}
schema_file: icdc.graphql
backend_user_info: https://caninecommons.cancer.gov/fence/login/
backend_fence_login: https://nci-crdc-staging.datacommons.io/user/oauth2/authorize?client_id={{ fence_id }}&response_type=code&redirect_uri=https%3A%2F%2Fcaninecommons.cancer.gov%2F&scope=openid%20user
backend_fence_logout: https://caninecommons.cancer.gov/fence/logout
backend_content_url: https://raw.githubusercontent.com/CBIIT/bento-icdc-frontend/master/src/content/{{ tier }}/aboutPagesContent.yaml
bento_api_version: "{{ backend_version }}"
backend_frontend_version: "{{frontend_version }}"
backend_google_analytics_id: UA-154442677-1
dev_alb_dns_name: internal-dev-a-appli-caninedata-8uhlkjyn-1830173970.us-east-1.elb.amazonaws.com
frontend_url: "{% if tier == 'prod' %}https://caninecommons.cancer.gov/{% else %}https://caninecommons-{{ tier }}.cancer.gov/{% endif %}" 
