version: '3.4'
services:
  aws-cdk:
    container_name: aws-cdk
    build:
      context: .
      dockerfile: ./dockerfiles/cdk_python
    environment:
      - AWS_ACCESS_KEY_ID=${aws_access_key_id}
      - AWS_SECRET_ACCESS_KEY=${aws_secret_access_key}
      - AWS_DEFAULT_REGION=${default_region}
    volumes:
      - ./bento:/bento