---
# vars file for neo4j-loader
backup_directory: /backups
remote_workspace: /tmp/neo4j
s3_bucket_name: "{{ lookup('env','S3_BUCKET') }}"
dump_file_name: "{{ lookup('env','DUMP_FILE') }}"
timestamp: "{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }}"

tier: "{{ lookup('env','TIER') }}"
region: us-east-1

icdc_cmd: '/var/lib/neo4j/bin/neo4j-admin'
std_cmd: 'neo4j-admin'
neo4j_admin_cmd: "{{ icdc_cmd if tier == 'icdc' else std_cmd }}"