- name: cds backend pipeline
  hosts: bento
  connection: local
  gather_facts: no
  become: yes

  tasks:
    - name: build stage for cds backend
      include_role:
        name: bento-cds
        tasks_from: build-backend
      vars:
        schema_file: bento-gmb.graphql
        ansible_python_interpreter: /usr/bin/python3