---
- name: bento cicd pipeline
  hosts: bento
  connection: local
  gather_facts: no
  become: yes
    
  tasks:
    - name: This is a build stage
      include_role:
        name: bento
        tasks_from: build
        vars_from: gmb