- name: cds backend pipeline
  hosts: bento
  connection: local
  gather_facts: no
  become: yes

  tasks:
    - name: build stage for gmb backend
      include_role:
        name: bento-cds
        tasks_from: build-frontend
      vars:
        ansible_python_interpreter: /usr/bin/python3