---
# defaults file for cicd
platform: aws
release: fail
project: icdc
prod: prod
# jq: "{{project}}.{{tier}}"
# alb_dns_name:
#   icdc:
#     dev: internal-dev-a-appli-caninedata-8uhlkjyn-1830173970.us-east-1.elb.amazonaws.com
#     qa: internal-qa-ca-appli-6p2vxovvw4sd-1727805720.us-east-1.elb.amazonaws.com


